package net.garmine.parser.html.tokenizer;

public enum HtmlTokenizerState {
	//===================[ATTRIBUTES]==================//
	
	BEFORE_ATTRIBUTE_NAME, 
	ATTRIBUTE_NAME, 
	AFTER_ATTRIBUTE_NAME, 

	BEFORE_ATTRIBUTE_VALUE, 
	ATTRIBUTE_VALUE_DOUBLE_QUOTED, 
	ATTRIBUTE_VALUE_SINGLE_QUOTED, 
	ATTRIBUTE_VALUE_UNQUOTED, 
	AFTER_ATTRIBUTE_VALUE_QUOTED, 
	
	//====================[DOCTYPE]====================//

	DOCTYPE, 
	
	BEFORE_DOCTYPE_NAME, 
	DOCTYPE_NAME, 
	AFTER_DOCTYPE_NAME, 

	AFTER_DOCTYPE_PUBLIC_KEYWORD, 
	BEFORE_DOCTYPE_PUBLIC_IDENTIFIER, 
	DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED, 
	DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED, 
	AFTER_DOCTYPE_PUBLIC_IDENTIFIER, 
	
	BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS, 

	AFTER_DOCTYPE_SYSTEM_KEYWORD, 
	BEFORE_DOCTYPE_SYSTEM_IDENTIFIER, 
	DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED, 
	DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED, 
	AFTER_DOCTYPE_SYSTEM_IDENTIFIER, 

	BOGUS_DOCTYPE, 
	

	//====================[COMMENT]====================//
	
	COMMENT_START, 
	COMMENT_START_DASH, 
	COMMENT, 
	COMMENT_END, 
	COMMENT_END_BANG, 
	COMMENT_END_DASH, 

	BOGUS_COMMENT, 
	
	//=====================[DATA]======================//
	
	DATA, 
	END_TAG_OPEN, 
	TAG_NAME, 
	TAG_OPEN,
	SELF_CLOSING_START_TAG,

	//====================[RAWTEXT]====================//
	
	RAWTEXT, 
	RAWTEXT_LESS_THAN, 
	RAWTEXT_END_TAG_OPEN, 
	RAWTEXT_END_TAG_NAME, 

	//====================[RCDATA]=====================//
	
	RCDATA, 
	RCDATA_LESS_THAN, 
	RCDATA_END_TAG_OPEN, 
	RCDATA_END_TAG_NAME, 
	
	//====================[SCRIPT]=====================//
	
	SCRIPT, 
	SCRIPT_LESS_THAN,
	
	SCRIPT_ESCAPE_START, 
	SCRIPT_ESCAPE_START_DASH, 

	SCRIPT_ESCAPED, 
	SCRIPT_ESCAPED_DASH,
	SCRIPT_ESCAPED_DASH_DASH, 
	SCRIPT_ESCAPED_LESS_THAN, 

	SCRIPT_DOUBLE_ESCAPE_START, 
	SCRIPT_DOUBLE_ESCAPED, 
	SCRIPT_DOUBLE_ESCAPED_DASH, 
	SCRIPT_DOUBLE_ESCAPED_DASH_DASH, 
	SCRIPT_DOUBLE_ESCAPED_LESS_THAN, 
	SCRIPT_DOUBLE_ESCAPE_END, 

	SCRIPT_ESCAPED_END_TAG_OPEN, 
	SCRIPT_ESCAPED_END_TAG_NAME,
	
	SCRIPT_END_TAG_OPEN, 
	SCRIPT_END_TAG_NAME, 

	//======================[ETC]======================//
	
	CDATA_SECTION, 
	MARKUP_DECL_OPEN, 
	PLAINTEXT
}
