package net.garmine.parser.html.elements;

public enum HtmlElementType {
	ABBR, ACRONYM, ADDRESS, A, APPLET, AREA, ARTICLE, ASIDE, AUDIO, 
	BASEFONT, BASE, BDI, BDO, BIG, B, BLOCKQUOTE, BODY, BR, BUTTON, 
	CANVAS, CAPTION, CENTER, CITE, CODE, COLGROUP, COL, COMMAND, COMPACT, 
	DATALIST, DD, DEL, DETAILS, DFN, DIALOG, DIV, DL, DT, 
	EMBED, EM, 
	FIELDSET, FIGCAPTION, FIGURE, FONT, FOOTER, FORM, FRAME, FRAMESET, 
	//G
	H1, H2, H3, H4, H5, H6, HEADER, HEAD, HR, HTML, 
	IFRAME, I, IMG, INPUT, INS, 
	//J
	KBD, KEYGEN, LABEL, LEGEND, 
	LI, LINK, 
	MAP, MARK, MENU, META, METER, 
	NAV, NOFRAMES, NOSCRIPT, 
	OBJECT, OL, OPTGROUP, OPTION, OUTPUT, 
	PARAM, P, PRE, PROGRESS, 
	Q, 
	RP, RT, RUBY, 
	SAMP, SCRIPT, SECTION, SELECT, S, SMALL, SOURCE, SPAN, STRIKE, STRONG, STYLE, SUB, SUMMARY, SUP, 
	TABLE, TBODY, TD, TEXTAREA, TFOOT, THEAD, TH, TIME, TITLE, TRACK, TR, TT, 
	U, UL, 
	VAR, VIDEO, 
	WBR;
	//X
	//Y
	//Z
}
